### ISSUE TITLE
发布版本了吗？

### ISSUE THREAD

**Issue by xiaohuoni** [yshkk/bqb-mpvue#4]
觉得很有趣，发布版本了吗？

**Comment by yshkk** [comment]
微信小程序搜索：“熊猫斗图助手”

**Comment by xiaohuoni** [comment]
扫码图片错误  https://camo.githubusercontent.com/9103a160806c94ed0e5787ee3b197159b3ba9f80/687474703a2f2f792e70686f746f2e71712e636f6d2f696d673f733d6a4456653262784862266c3d792e6a7067

**Comment by yshkk** [comment]
我也发现了这张图片 有时抽风 有时可以😂
